name: Regular pipeline

permissions:
  contents: read
  id-token: write
  pages: write

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-prepare-${{ env.cache-name }}-${{ github.sha }}

      - name: Set Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Set NPM version
        run: npm i -g npm@7

      - name: Install dependencies
        run: npm ci

  lint:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use node modules cache
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-prepare-${{ env.cache-name }}-${{ github.sha }}

      - name: Run Eslint
        run: npm run lint

  deploy:
    needs: [lint]

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use node modules cache
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-prepare-${{ env.cache-name }}-${{ github.sha }}

      - name: Build dist
        run: npm run build

      - name: Rename public directory
        run: mv public public-vue

      - name: Rename dist to public
        run: mv dist public
        
      - name: Set ENV
        run: echo "PROJECT_NAME=$PROJECT_NAME" >> dist/.env

      - name: Activate GZip support
        run: find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
        
      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
